{{- if .Values.networkPolicies.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
 name: {{ .Release.Name }}-default-deny-all
 namespace: mca-app
spec:
 podSelector: {}
 ingress: []
 egress: [] 
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-allow-external
 namespace: mca-app
spec:
 podSelector: 
   matchLabels:
     app: server
 ingress: 
   - from: []
 policyTypes:
   - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-worker-allow-rabbit
 namespace: mca-app
spec:
 podSelector:
   matchLabels:
     app: worker
 egress:
 - to:     
   - podSelector:
       matchLabels:
         app: rabbitmq
 - ports:
   - port: 5672
     protocol: TCP
 policyTypes:
 - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-worker-allow-mysql
 namespace: mca-app
spec:
 podSelector:
   matchLabels:
     app: worker
 egress:
 - to:     
   - podSelector:
       matchLabels:
         app: mysql
 - ports:
   - port: 3306
     protocol: TCP
 policyTypes:
 - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-rabbit-allow
 namespace: mca-app
spec:
 podSelector:
   matchLabels:
     app: rabbitmq
 ingress:
 - from: 
    - podSelector:
       matchLabels:
         app: worker
    - podSelector:
        matchLabels:
          app: server
 - ports:
   - port: 5672
     protocol: TCP
 policyTypes:
   - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-mysql-allow
 namespace: mca-app
spec:
 podSelector:
   matchLabels:
     app: mysql
 ingress:
 - from:
    - podSelector:  
        matchLabels:
          app: worker
 - ports:
   - protocol: TCP
     port: 3306
 policyTypes:
   - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-mongo-allow
 namespace: mca-app
spec:
 podSelector:
   matchLabels:
     app: mongo
 ingress:
 - from:
   - podSelector:
       matchLabels:
         app: server
 - ports:
   - protocol: TCP
     port: 27017
 policyTypes:
   - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-external-service-2-worker
 namespace: mca-app
spec:
 podSelector:
   matchLabels:
     app: external-service
 egress:
 - to:
   - podSelector:
       matchLabels:
         app: worker
   ports:
   - port: 9090
     protocol: TCP
 policyTypes:
   - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: {{ .Release.Name }}-worker-2-external-service
 namespace: mca-app
spec:
 podSelector:
   matchLabels:
     app: worker
 ingress:
   - from:
     - podSelector:
         matchLabels:
           app: external-service
     ports:
     - port: 9090
       protocol: TCP
 policyTypes:
   - Ingress
{{- end }}